Header & Footer
ZuhRa-HashiMi/JS_Capastone pull request #22
Opened 2022-11-29 09:58 UTC by ZuhRa-HashiMi

make the header section
make the footer section

2022-11-29 10:47 UTC, Tadesse-Alemayehu reviewed
### Hi @ZuhRa-HashiMi  

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
![yPkfDFf](https://user-images.githubusercontent.com/69077061/204103543-ee5d8fa8-a37f-4177-b602-f22a28e022fb.gif)

You have submitted a project that has linter tests falling. Please make sure all linters are set up and passing before your next review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-01 08:17 UTC, Ofarouq310 requested changes
# Status: Failed ❌ 
Hi @ZuhRa-HashiMi  ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.


## Invalid Code Review Request 🛑🛑

![giphy](https://user-images.githubusercontent.com/102612396/205000837-870d81ab-2c0c-4acb-b911-25964391a53b.gif)

You have submitted a project that has linter tests falling. Please make sure all linters are set up and passing before your next review request.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

2022-12-01 09:43 UTC, Ofarouq310 commented on src/index.html
> +          </div>
- [ ] Kindly change the footer's inner text as you have to follow the required wireframe:
 
![image](https://user-images.githubusercontent.com/102612396/205019590-bbd1389b-33ad-47ee-bd80-5042fa081273.png)

2022-12-01 09:44 UTC, Ofarouq310 requested changes
Hi @ZuhRa-HashiMi  ,

Great job so far!
You are almost there,  just a couple of simple issues we need to discuss together!

## Highlights 💯
No linters errors ✔️
Following Gitflow ✔️
Following HTML, CSS best practices ✔️

## Required Changes ♻️
- [ ] Kindly fix the disappearing icon at the top left of the page to make it visible.

- [ ] Kindly rename your branch name from 'master' and give it any name according to the feature you are implementing, like 'header-footer' as an example.

- _Please, Check the comments under the review._



## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-01 09:46 UTC, Ofarouq310 requested changes
Hi @ZuhRa-HashiMi  ,

Great job so far!
You are almost there,  just a couple of simple issues we need to discuss together!

## Highlights 💯
No linters errors ✔️
Following Gitflow ✔️
Following HTML, CSS best practices ✔️

## Required Changes ♻️
- [ ] Kindly fix the disappearing icon at the top left of the page to make it visible.

- [ ] Kindly rename your branch name from 'master' and give it any name according to the feature you are implementing, like 'header-footer' as an example.

- _Please, Check the comments under the review._



## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-01 09:46 UTC, Ofarouq310 commented on src/index.html
> +          </div>
- [ ] Kindly change the footer's inner text as you have to follow the required wireframe:
 
![image](https://user-images.githubusercontent.com/102612396/205019590-bbd1389b-33ad-47ee-bd80-5042fa081273.png)

2022-12-01 14:29 UTC, Ofarouq310 approved these changes
# Status: Approved 🎉 ✔️
Hi @ZuhRa-HashiMi  ,

Your milestone is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![giphy](https://user-images.githubusercontent.com/102612396/201940266-f63313a0-497d-46fd-a04f-9cdfa0934d7d.gif)

## Highlights
No linter errors. ✔️
Good README file. ✔️
Milestone worked as expected. ✔️


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

<hr>

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-01 14:30 UTC, merged